# Generated by Django 6.0.6 on 2026-06-05 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='buy', max_length=10)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20)),
                ('property_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('draft', 'Draft')], default='active', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_label', models.CharField(blank=True, max_length=30)),
                ('price_period', models.CharField(blank=True, max_length=20)),
                ('bhk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('facing', models.CharField(blank=True, max_length=30)),
                ('furnishing', models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi-furnished', 'Semi-Furnished'), ('fully-furnished', 'Fully-Furnished'), ('fully-fitted', 'Fully Fitted')], max_length=20)),
                ('parking', models.PositiveSmallIntegerField(default=0)),
                ('age', models.CharField(blank=True, max_length=30)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('consultant_name', models.CharField(blank=True, max_length=100)),
                ('consultant_title', models.CharField(blank=True, max_length=100)),
                ('consultant_initials', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('property_ref', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=12)),
                ('source', models.CharField(choices=[('website', 'Website'), ('phone', 'Phone'), ('walk-in', 'Walk-In'), ('referral', 'Referral')], default='website', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='core.property')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
